services:
  dimension-erp:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - .env:/usr/src/app/.env
    command: bash -c "yarn install && yarn start"
    container_name: dimension
    environment:
      - NODE_ENV=development
    networks:
      - my-custom-network

networks:
  my-custom-network:
    external: true
